// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSolutionsLab.OrangeCarRental.Pricing.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.OrangeCarRental.Pricing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.OrangeCarRental.Pricing.Domain.PricingPolicy.PricingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PricingPolicyId");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CategoryCode");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveFrom");

                    b.Property<DateTime?>("EffectiveUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveUntil");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LocationCode");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DailyRate", "SmartSolutionsLab.OrangeCarRental.Pricing.Domain.PricingPolicy.PricingPolicy.DailyRate#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("NetAmount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DailyRateNet");

                            b1.Property<decimal>("VatAmount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DailyRateVat");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .HasDatabaseName("IX_PricingPolicies_CategoryCode");

                    b.HasIndex("CategoryCode", "IsActive")
                        .HasDatabaseName("IX_PricingPolicies_CategoryCode_IsActive");

                    b.HasIndex("CategoryCode", "LocationCode", "IsActive")
                        .HasDatabaseName("IX_PricingPolicies_CategoryCode_LocationCode_IsActive");

                    b.ToTable("PricingPolicies", "pricing");
                });
#pragma warning restore 612, 618
        }
    }
}
