name: 'Setup Frontend'
description: 'Setup Node.js and install frontend dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'
  working-directory:
    description: 'Working directory for yarn commands'
    required: false
    default: 'src/frontend'
  skip-puppeteer:
    description: 'Skip Puppeteer download'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn install --frozen-lockfile
      env:
        PUPPETEER_SKIP_DOWNLOAD: ${{ inputs.skip-puppeteer }}
