// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSolutionsLab.OrangeCarRental.Reservations.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.OrangeCarRental.Reservations.Infrastructure.Migrations
{
    [DbContext(typeof(ReservationsDbContext))]
    [Migration("20251205203650_UpgradeToEfCore10")]
    partial class UpgradeToEfCore10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reservations")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.OrangeCarRental.Reservations.Domain.Reservation.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReservationId");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CancellationReason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ConfirmedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CustomerIdentifier")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("DropoffLocationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DropoffLocationCode");

                    b.Property<string>("PickupLocationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PickupLocationCode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<Guid>("VehicleIdentifier")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "SmartSolutionsLab.OrangeCarRental.Reservations.Domain.Reservation.Reservation.Period#BookingPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("PickupDate")
                                .HasColumnType("date")
                                .HasColumnName("PickupDate");

                            b1.Property<DateOnly>("ReturnDate")
                                .HasColumnType("date")
                                .HasColumnName("ReturnDate");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "SmartSolutionsLab.OrangeCarRental.Reservations.Domain.Reservation.Reservation.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("NetAmount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalPriceNet");

                            b1.Property<decimal>("VatAmount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalPriceVat");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerIdentifier");

                    b.HasIndex("DropoffLocationCode");

                    b.HasIndex("PickupLocationCode");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleIdentifier");

                    b.ToTable("Reservations", "reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
